name: WeaponsPlus
main: WeaponsPlus\Main
version: 1.0.1
api: [2.0.0]
author: MCPEPIG
permissions:
  weaponsplus:
    default: op
    description: "Allows using all WeaponsPlus features"
    children:
      weaponsplus.command:
        default: op
        description: "Allows using all weapons"
        children:
          weaponsplus.command.effectblades:
            default: op
            description: "Allows using EffectBlades"
          weaponsplus.command.grenades:
            default: op
            description: "Allows using Grenades"
          weaponsplus.command.bazukas:
            default: op
            description: "Allows using Bazukas"
