name: WeaponsPlus
main: MCPEPIG\WeaponsPlus\Main
version: 1.0.0
api: [1.12.0]
load: POSTWORLD
author: MCPEPIG
permissions:
  weaponsplus:
    default: op
    description: "Everything :P"
    children:
      weaponsplus.flamebows.use:
        default: true
        description: "Lets you use flamebows"
      weaponsplus.effectblades.use:
        default: true
        description: "Lets you use effectblades"
