#                                                                                                                                 
#                                                                                  ,-.----.                                       
#           .---.                                                                  \    /  \    ,--,                              
#          /. ./|                       ,-.----.                                   |   :    \ ,--.'|                              
#      .--'.  ' ;                       \    /  \    ,---.        ,---,            |   |  .\ :|  | :            ,--,              
#     /__./ \ : |                       |   :    |  '   ,'\   ,-+-. /  | .--.--.   .   :  |: |:  : '          ,'_ /|   .--.--.    
# .--'.  '   \' .   ,---.     ,--.--.   |   | .\ : /   /   | ,--.'|'   |/  /    '  |   |   \ :|  ' |     .--. |  | :  /  /    '   
#/___/ \ |    ' '  /     \   /       \  .   : |: |.   ; ,. :|   |  ,"' |  :  /`./  |   : .   /'  | |   ,'_ /| :  . | |  :  /`./   
#;   \  \;      : /    /  | .--.  .-. | |   |  \ :'   | |: :|   | /  | |  :  ;_    ;   | |`-' |  | :   |  ' | |  . . |  :  ;_     
# \   ;  `      |.    ' / |  \__\/: . . |   : .  |'   | .; :|   | |  | |\  \    `. |   | ;    '  : |__ |  | ' |  | |  \  \    `.  
#  .   \    .\  ;'   ;   /|  ," .--.; | :     |`-'|   :    ||   | |  |/  `----.   \:   ' |    |  | '.'|:  | : ;  ; |   `----.   \ 
#   \   \   ' \ |'   |  / | /  /  ,.  | :   : :    \   \  / |   | |--'  /  /`--'  /:   : :    ;  :    ;'  :  `--'   \ /  /`--'  / 
#    :   '  |--" |   :    |;  :   .'   \|   | :     `----'  |   |/     '--'.     / |   | :    |  ,   / :  ,      .-./'--'.     /  
#     \   \ ;     \   \  / |  ,     .-./`---'.|             '---'        `--'---'  `---'.|     ---`-'   `--`----'      `--'---'   
#      '---"       `----'   `--`---'      `---`                                      `---`                                        
#        

#If enabled, effect blades will fuction
effect-blades: true
#If enabled, effect blades will be enabled automatically
auto-enable-eb: true
#Your effect blades (Format: "id:damagevalue:effectid:amplifier:time:particles")
effects: 
- "276:0:2:5:5:false"
- "272:0:20:5:5:false"
#If enabled, grenades will function
grenades: true
#If enabled, grenades will be enabled automatically
auto-enable-grenades: true
#Strength of grenade explosion
grenade-strength: 4
#If enabled, grenades will effect terrain (Terrain damage can be restored if you  have BadPiggy)
terrain-damage: false
#If enabled, landmines will fuction
landmines: true
#Block for landmine
landmine: 151
#If enabled, grenades will be enabled automatically
auto-enable-landmines: true
#Strength of landmine explosion
landmine-strength: 4
#If enabled, spears will fuction
spears: true
#Item for spears
spear: 262
#If enabled, spears will be enabled automatically
auto-enable-spears: true
#Damage for spears
spear-damage: 7
#If enabled, bazukas will function
bazukas: true
#Item for bazuka
bazuka: 369
#If enabled, bazukas will be enabled automatically
auto-enable-bazukas: true
#If enabled, enderpearls will function
enderpearls: true
#If enabled, enderpearls will be enabled automatically
auto-enable-enderpearls: true
#If enabled, weapons must have a certain name to function
name-required: true